import { AppConfig } from './Models/AppConfig';
import type { Profile } from './Models/Profile';
import type { Order } from './Models/Order';
export declare function setConfig(appConfig: AppConfig): Promise<void>;
export declare function getAccessToken(): Promise<any>;
export declare function sendTwoFactor(mobile: string): Promise<unknown>;
export declare function verifyTwoFactor(code: string): Promise<unknown>;
export declare function getBrand(): Promise<unknown>;
export declare function getCatalogue(): Promise<unknown>;
export declare function getBalance(cardId: string): Promise<unknown>;
export declare function getTransactions(cardId: string): Promise<unknown>;
export declare function getCardDetails(cardId: string): Promise<unknown>;
export declare function createProfile(user: Profile): Promise<unknown>;
export declare function createOrder(order: Order): Promise<unknown>;
export declare function searchCards(mobile: string): Promise<unknown>;
export declare function getProfile(userId: string): Promise<unknown>;
export declare function updateProfile(user: Profile): Promise<unknown>;
export declare function getOrders(user_id: string): Promise<unknown>;
export declare function cardCallBack(callBackUrl: string, token: string): Promise<unknown>;
